### ISSUE TITLE
KeyEerror when ran kraken2

### ISSUE THREAD

**Issue by linss123** [DerrickWood/kraken2#495]
Hello
This is a user of Kraken2.
PlusPF database was downloaded in 'https://benlangmead.github.io/aws-indexes/k2' , and the taxonomy information were installed  using `kraken2-build --download-taxonomy` .
But I kept getting KeyError when Kraken2 ran throught metawrap.
```
metawrap kraken2 -o KRAKEN/LY -t 12 ASSEMBLY/LY/final_assembly.fasta

##################################################################################################################                         ######
#####                                          RUNNING KRAKEN ON ALL FILES                                                                  #####
##################################################################################################################                         ######


------------------------------------------------------------------------------------------------------------------                         ------
-----                        Now processing ASSEMBLY/LY/final_assembly.fasta with 12 threads                                                -----
------------------------------------------------------------------------------------------------------------------                         ------

kraken2 --use-names --db /home/zms/db/MY_KRAKEN_DATABASE --threads 12 --output KRAKEN/LY/final_assembly.krak2 ASSE                         MBLY/LY/final_assembly.fasta
Loading database information... done.
243541 sequences (528.61 Mbp) processed in 6.299s (2319.9 Kseq/m, 5035.31 Mbp/m).
  178788 sequences classified (73.41%)
  64753 sequences unclassified (26.59%)

########################################################################################################################
#####                                      RUNNING KRAKEN-TRANSLATE ON OUTPUT                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                  Translating KRAKEN/LY/final_assembly.krak2                                  -----
------------------------------------------------------------------------------------------------------------------------

Translating kraken2 annotations from KRAKEN/LY/final_assembly.krak2, using metadata from the kraken2 database in /home/zms/db/MY_KRAKEN_DATABASE; saving to KRAKEN/LY/final_assembly.kraken2
Translating kraken2 annotations
Loading NCBI node names
Loading NCBI taxonomic ranks
Writing translated taxonomy names to KRAKEN/LY/final_assembly.kraken2
Traceback (most recent call last):
  File "/home/zms/miniconda3/envs/metawrap/bin/metawrap-scripts/kraken2_translate.py", line 120, in <module>
    main()
  File "/home/zms/miniconda3/envs/metawrap/bin/metawrap-scripts/kraken2_translate.py", line 114, in main
    translate_kraken2_annotations(annotation_file=kraken_file, kraken2_db=database_location, output=output_file)
  File "/home/zms/miniconda3/envs/metawrap/bin/metawrap-scripts/kraken2_translate.py", line 98, in translate_kraken2_annotations
    taxonomy = get_full_name(taxid, names_map, ranks_map)
  File "/home/zms/miniconda3/envs/metawrap/bin/metawrap-scripts/kraken2_translate.py", line 30, in get_full_name
    name = names_map[taxid]
KeyError: '1418105'

************************************************************************************************************************
*****                        Something went wrong with running kraken-translate... Exiting.                        *****
************************************************************************************************************************
```
May I know what is the problem and how to deal with it ?
Thanks a lot !

**Comment by kuangzhuoran** [comment]
Hi ! I met the same error, Have u resolved that?? Thanks

**Comment by linss123** [comment]
I have resolved that by not using kraken2&nbsp; throught metawrap. Maybe there is something wrong with the workflow.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DerrickWood/kraken2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DerrickWood/kraken2] KeyEerror when ran kraken2 (#495)





 
Hi ! I met the same error, Have u resolved that?? Thanks
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuangzhuoran** [comment]
Hi ! Thanks a lot !!!
It works perfectly


And I just found the relevant information -- https://blog.csdn.net/qq_23341021/article/details/120171438
I didn't look at this page carefully. It may be helpful.
Overall, kraken2's goal has been achieved

**Comment by linss123** [comment]
Yeah！
I found there are many faults in the workflow. You would better use original software excepting binning and assembling。
good luck!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DerrickWood/kraken2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DerrickWood/kraken2] KeyEerror when ran kraken2 (#495)





 
Hi ! Thanks a lot !!!
 It works perfectly
 
And I just found the relevant information -- https://blog.csdn.net/qq_23341021/article/details/120171438
 I didn't look at this page carefully. It may be helpful.
 Overall, kraken2's goal has been achieved
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
