### ISSUE TITLE
make_kreport.py: KeyError

### ISSUE THREAD

**Issue by Kodjovidodji** [DerrickWood/kraken2#580]
I keep having this errors while generating report from kraken file (kraken2)
PROGRAM START TIME: 04-13-2022 02:31:36
>> STEP 1/4: Reading taxonomy ~/DB/k2_16G_db/mydb_taxonomy.txt...
        32363 nodes saved
>> STEP 2/4: Reading kraken file diversity_analysis/all.kraken...
        0.029 million reads processed
>> STEP 3/4: Creating final tree...
Traceback (most recent call last):
  File "KrakenTools/make_kreport.py", line 199, in <module>
    main()
  File "KrakenTools/make_kreport.py", line 145, in main
    p_node = taxid2node[curr_tid].parent 
KeyError: '2736602'

**Comment by jenniferlu717** [comment]
This is a KrakenTools error but can you email me directly: jennifer.lu717@gmail.com with the taxonomy file?
